language: nodejs

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t clblount9/micro-feed-service-test ./microservices/feed/
  - docker push clblount9/micro-feed-service-test
