version: "3"
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
        - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
  reverseproxy:
      image: clblount9/micro-apigateway-service-test
      ports:
          - 8080:8080
      restart: always
#      depends_on:
#        - backend-user
#        - backend-feed     
#  backend-user:
#    image: clblount9/micro-user-service-test
#    environment:
#      - POSTGRES_USERNAME
#      - POSTGRES_PASSWORD
#      - POSTGRES_DB
#      - POSTGRES_HOST
#      - AWS_REGION
#      - AWS_PROFILE
#      - AWS_BUCKET
#      - JWT_SECRET
#      - URL="http://localhost:8100"
#  backend-feed:
#    image: clblount9/micro-feed-service-test
#    volumes:
#      - $HOME/.aws:/root/.aws
#    environment:
#      - POSTGRES_USERNAME
#      - POSTGRES_PASSWORD
#      - POSTGRES_DB
#      - POSTGRES_HOST
#      - AWS_REGION
#      - AWS_PROFILE
#      - AWS_BUCKET
#      - JWT_SECRET
#      - URL="http://localhost:8100"
  frontend:
    image: clblount9/micro-frontend-service-test
    ports:
      - "8100:80"
